# ------------------------------------------------------------
# R script: 02_compare_population_sources
# - Compares GPW vs WorldPop population values per Thiessen polygon (per year)
# - Uses shapefiles generated by 01_aggregate_population
# - Expects columns: pop_gpw (GPW) and pp_wrld (WorldPop, truncated by shapefile)
# - Outputs summary statistics and scatterplots per year
# ------------------------------------------------------------

suppressPackageStartupMessages({
  library(sf)
  library(dplyr)
  library(ggplot2)
  library(tools)
})

# ----------------------------
# 0) Paths
# ----------------------------
dir_in  <- "C:/Users/d.millanorduz/OneDrive - Universidad de los Andes/Diana_CESED/rutas/modeling_routes_CESED/02_exit_points/03_aggregate_population/output"
dir_out <- file.path(dirname(dir_in), "04_compare_population")
if (!dir.exists(dir_out)) dir.create(dir_out, recursive = TRUE, showWarnings = FALSE)

out_csv <- file.path(dir_out, "population_comparison_summary.csv")

# ----------------------------
# 1) List shapefiles thiessen_YYYY_pop.shp
# ----------------------------
list_pop_shapes <- list.files(
  dir_in,
  pattern = "^thiessen_\\d{4}_pop\\.shp$",
  full.names = TRUE
)

if (length(list_pop_shapes) == 0) stop("No population shapefiles found in output folder.")

summary_results <- data.frame()

# ----------------------------
# 2) Loop per year
# ----------------------------
for (f in list_pop_shapes) {
  yy <- as.integer(gsub("\\D", "", basename(f)))  # extract year from filename
  cat("Processing:", basename(f), "\n")
  
  shp <- st_read(f, quiet = TRUE)
  
  # Check that expected columns exist
  cols <- names(shp)
  if (!all(c("pop_gpw", "pp_wrld") %in% cols)) {
    stop(paste(
      "Expected columns 'pop_gpw' and 'pp_wrld' not found in",
      basename(f),
      "\nColumns present are:", paste(cols, collapse = ", ")
    ))
  }
  
  # Drop geometry for numeric summaries
  shp_df <- shp %>%
    st_drop_geometry() %>%
    filter(!is.na(pop_gpw), !is.na(pp_wrld))
  
  if (nrow(shp_df) == 0) {
    cat("  > No valid records with both pop_gpw and pp_wrld for year", yy, "- skipped.\n")
    next
  }
  
  # --- Compute metrics ---
  shp_df <- shp_df %>%
    mutate(
      diff_abs  = pp_wrld - pop_gpw,
      diff_perc = (pp_wrld - pop_gpw) / pop_gpw * 100,
      ratio     = pp_wrld / pop_gpw
    )
  
  # --- Summary statistics ---
  corr <- cor(shp_df$pop_gpw, shp_df$pp_wrld, use = "complete.obs")
  mean_diff_abs  <- mean(shp_df$diff_abs, na.rm = TRUE)
  mean_diff_perc <- mean(shp_df$diff_perc, na.rm = TRUE)
  median_ratio   <- median(shp_df$ratio, na.rm = TRUE)
  
  summary_results <- rbind(
    summary_results,
    data.frame(
      year = yy,
      correlation   = round(corr, 3),
      mean_diff_abs = round(mean_diff_abs, 2),
      mean_diff_perc = round(mean_diff_perc, 2),
      median_ratio  = round(median_ratio, 3),
      stringsAsFactors = FALSE
    )
  )
  
  # --- Scatterplot GPW vs WorldPop ---
  p <- ggplot(shp_df, aes(x = pop_gpw, y = pp_wrld)) +
    geom_point(alpha = 0.5, color = "#4A7EBB") +
    geom_abline(intercept = 0, slope = 1, color = "red", linetype = "dashed") +
    labs(
      title    = paste("Population comparison:", yy),
      subtitle = "GPW (pop_gpw) vs WorldPop (pp_wrld) per Thiessen polygon",
      x        = "GPW population (pop_gpw)",
      y        = "WorldPop population (pp_wrld)"
    ) +
    theme_minimal()
  
  plot_path <- file.path(dir_out, sprintf("scatter_population_%d.png", yy))
  ggsave(plot_path, plot = p, width = 6, height = 5, dpi = 300)
  cat("  > Saved plot:", basename(plot_path), "\n")
}

# ----------------------------
# 3) Save summary CSV
# ----------------------------
write.csv(summary_results, out_csv, row.names = FALSE)
cat("Summary saved to:", out_csv, "\n")

print(summary_results)




# ------------------------------------------------------------
# R script: 05_plot_population_ratios.R
# - Visualize the ratio WorldPop / GPW per Thiessen polygon (per year)
# - Input: shapefiles from 03_aggregate_population/output
# - Output: boxplot and violin plot by year
# ------------------------------------------------------------

suppressPackageStartupMessages({
  library(sf)
  library(dplyr)
  library(ggplot2)
})

# ----------------------------
# 0) Paths
# ----------------------------
dir_in <- "C:/Users/d.millanorduz/OneDrive - Universidad de los Andes/Diana_CESED/rutas/modeling_routes_CESED/02_exit_points/03_aggregate_population/output"
dir_out <- file.path(dirname(dir_in), "05_plot_population_ratios")
if (!dir.exists(dir_out)) dir.create(dir_out, recursive = TRUE, showWarnings = FALSE)

# ----------------------------
# 1) Read all population shapefiles
# ----------------------------
files <- list.files(dir_in, pattern = "^thiessen_\\d{4}_pop\\.shp$", full.names = TRUE)
if (length(files) == 0) stop("No population shapefiles found in folder.")

# Prepare empty data frame
ratio_df <- data.frame()

for (f in files) {
  yy <- as.integer(gsub("\\D", "", basename(f)))  # extract year
  cat("Reading:", basename(f), "\n")
  
  shp <- st_read(f, quiet = TRUE)
  
  # Check expected fields (remember shapefile truncation)
  if (!all(c("pop_gpw", "pp_wrld") %in% names(shp))) {
    warning(paste("Missing expected columns in", basename(f)))
    next
  }
  
  # Compute ratio and keep relevant columns
  tmp <- shp %>%
    st_drop_geometry() %>%
    filter(pop_gpw > 0, pp_wrld >= 0) %>%
    mutate(
      year = yy,
      ratio = pp_wrld / pop_gpw
    ) %>%
    select(year, ratio)
  
  ratio_df <- rbind(ratio_df, tmp)
}

# ----------------------------
# 2) Plot: boxplot + violin
# ----------------------------
p <- ggplot(ratio_df, aes(x = factor(year), y = ratio)) +
  geom_violin(fill = "#E0E0FF", color = NA, alpha = 0.6) +
  geom_boxplot(width = 0.2, fill = "#4A7EBB", color = "black", outlier.shape = NA) +
  geom_hline(yintercept = 1, linetype = "dashed", color = "red") +
  labs(
    title = "Ratio of WorldPop to GPW Population per Thiessen Polygon",
    subtitle = "Values below 1 indicate WorldPop < GPW",
    x = "Year",
    y = "Ratio (WorldPop / GPW)"
  ) +
  theme_minimal(base_size = 13)

# Save figure
plot_path <- file.path(dir_out, "population_ratio_by_year.png")
ggsave(plot_path, p, width = 7, height = 5, dpi = 300)

cat("??? Plot saved at:", plot_path, "\n")
